#!/usr/bin/env bash
set -euo pipefail

repo=$(cd -P -- "$(dirname -- "$0")/.." && pwd)
work=$(mktemp -d '/tmp/pkl-nix-tools-test.XXXXXXXX')
trap 'rm -rf -- "$work"' EXIT
mkdir -p "$work/bin" "$work/project with spaces"
project=$work/project\ with\ spaces
real_nix=$(command -v nix)
real_pkl=$(command -v pkl)

cat > "$work/bin/nix" <<'EOF'
#!/usr/bin/env bash
if [[ " $* " == *' hash file '* ]]; then exec "$REAL_NIX" "$@"; fi
printf '%s\0' "$@" > "$TOOL_TEST_LOG"
exit "${TOOL_TEST_EXIT:-0}"
EOF
cat > "$work/bin/pkl" <<'EOF'
#!/usr/bin/env bash
if [[ ${TOOL_TEST_NO_PKL:-0} == 1 ]]; then exit 99; fi
exec "$REAL_PKL" "$@"
EOF
chmod +x "$work/bin/nix" "$work/bin/pkl"
export REAL_NIX=$real_nix REAL_PKL=$real_pkl TOOL_TEST_LOG=$work/nix.args
export PATH="$repo/pkl-nix-tools:$work/bin:$PATH"

cat > "$project/flake.pkl" <<EOF
#!/usr/bin/env -S pkl-nix-tools
amends "$repo/pkl-nix/Flake.pkl"
import "value.pkl" as Value
description = Value.description
EOF
chmod +x "$project/flake.pkl"
printf 'description = "first"\n' > "$project/value.pkl"

cd "$project"
./flake.pkl generate
[[ $(head -n 1 .pkl-nix-tools/flake.nix) == '# GENERATED BY pkl-nix-tools FROM flake.pkl. DO NOT EDIT.' ]]
grep -q 'description = "first"' .pkl-nix-tools/flake.nix
[[ ! -e flake.nix && ! -e .pkl-nix-tools/flake.lock ]]
nix-instantiate --parse .pkl-nix-tools/flake.nix >/dev/null

export TOOL_TEST_NO_PKL=1
./flake.pkl build .#hello --no-link
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *' build '* ]]
[[ " ${argv[*]} " == *"path:${project// /%20}?dir=.pkl-nix-tools#hello"* ]]
[[ " ${argv[*]} " == *"$project/flake.lock"* ]]

./flake.pkl build --out-link 'result with spaces'
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *"path:${project// /%20}?dir=.pkl-nix-tools --out-link result with spaces"* ]]

./flake.pkl develop --command bash -c true
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *"path:${project// /%20}?dir=.pkl-nix-tools --command bash -c true"* ]]

./flake.pkl flake update
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *"flake update"* ]]
[[ " ${argv[*]} " == *"--flake path:${project// /%20}?dir=.pkl-nix-tools"* ]]

if TOOL_TEST_EXIT=37 ./flake.pkl run .#hello; then exit 1; else
  [[ $? == 37 ]]
fi

unset TOOL_TEST_NO_PKL
printf 'description = "second"\n' > value.pkl
./flake.pkl build
grep -q 'description = "second"' .pkl-nix-tools/flake.nix

rm -rf .pkl-nix-tools
./flake.pkl generate
[[ -f .pkl-nix-tools/flake.nix && -f .pkl-nix-tools/fingerprint ]]

(
  cd "$repo/pkl-nix-tools/example"
  ./flake.pkl generate
  nix-instantiate --parse .pkl-nix-tools/flake.nix >/dev/null
  grep -Fq '../message.txt' .pkl-nix-tools/flake.nix
  [[ -f flake.lock && ! -e flake.nix && ! -e .pkl-nix-tools/flake.lock ]]
  rm -rf .pkl-nix-tools
)

mkdir -p "$work/install"
printf 'ID=debian\n' > "$work/install/os-release"
for attempt in 1 2; do
  PKL_NIX_TOOLS_OS_RELEASE_FILE="$work/install/os-release" \
  PKL_NIX_TOOLS_NIXOS_MARKER="$work/install/no-marker" \
  PKL_NIX_TOOLS_BASE_URL="file://$repo/pkl-nix-tools" \
  PKL_NIX_TOOLS_INSTALL_DIR="$work/install/share/pkl-nix-tools" \
  PKL_NIX_TOOLS_BIN_DIR="$work/install/bin" \
  HOME="$work/install" sh "$repo/pkl-nix-tools/install.sh" >/dev/null
done
[[ -L $work/install/bin/pkl-nix-tools ]]
PATH="$work/install/bin:$PATH" ./flake.pkl generate
[[ -f .pkl-nix-tools/flake.nix ]]
touch "$work/install/nixos-marker"
output=$(PKL_NIX_TOOLS_NIXOS_MARKER="$work/install/nixos-marker" sh "$repo/pkl-nix-tools/install.sh")
[[ $output == *'github.com/Agence-Fluor/pkl-nix-tools#nixos'* ]]

printf 'pkl-nix-tools tests passed\n'
