#!/usr/bin/env bash
set -euo pipefail

repo=$(cd -P -- "$(dirname -- "$0")" && pwd)
export JAVA_TOOL_OPTIONS="${JAVA_TOOL_OPTIONS:+$JAVA_TOOL_OPTIONS }-XX:-UsePerfData"
work=$(mktemp -d '/tmp/pkl-nix-tools-test.XXXXXXXX')
trap 'rm -rf -- "$work"' EXIT
mkdir -p "$work/bin" "$work/project with spaces"
project=$work/project\ with\ spaces
real_nix=$(command -v nix)
real_pkl=$(command -v pkl)

cat > "$work/bin/nix" <<'EOF'
#!/usr/bin/env bash
if [[ " $* " == *' hash file '* ]]; then exec "$REAL_NIX" "$@"; fi
if [[ " $* " == *' flake lock '* ]]; then
  printf '%s\0' "$@" > "$TOOL_TEST_LOCK_LOG"
  previous=
  for arg in "$@"; do
    if [[ $previous == --output-lock-file ]]; then printf '{"nodes":{"root":{}},"root":"root","version":7}\n' > "$arg"; fi
    previous=$arg
  done
  exit 0
fi
printf '%s\0' "$@" > "$TOOL_TEST_LOG"
exit "${TOOL_TEST_EXIT:-0}"
EOF
cat > "$work/bin/pkl" <<'EOF'
#!/usr/bin/env bash
if [[ ${TOOL_TEST_NO_PKL:-0} == 1 ]]; then exit 99; fi
exec "$REAL_PKL" "$@"
EOF
chmod +x "$work/bin/nix" "$work/bin/pkl"
export REAL_NIX=$real_nix REAL_PKL=$real_pkl TOOL_TEST_LOG=$work/nix.args TOOL_TEST_LOCK_LOG=$work/nix-lock.args
export PATH="$repo:$work/bin:$PATH"

head -n 1 "$repo/flake.pkl" > "$project/flake.pkl"
cat >> "$project/flake.pkl" <<EOF
import "value.pkl" as Value
local launcher = import("$repo/Bootstrap.pkl").output.text
output {
  text = "{ description = \"" + Value.description + "\"; outputs = { self, ... }: { }; }"
}
EOF
chmod +x "$project/flake.pkl"
printf 'description = "first"\n' > "$project/value.pkl"
printf 'amends "pkl:Project"\n' > "$project/PklProject"

cd "$project"
./flake.pkl --help > "$work/help.txt"
grep -Fq './flake.pkl generate|build|develop|run|flake' "$work/help.txt"
if ./flake.pkl > "$work/bare.txt" 2>&1; then exit 1; else [[ $? == 2 ]]; fi
[[ ! -e .pkl-nix-tools/flake.nix && ! -e $TOOL_TEST_LOG ]]
TOOL_TEST_NO_PKL=1 ./flake.pkl --help >/dev/null
pkl eval flake.pkl > "$work/rendered.nix"
nix-instantiate --parse "$work/rendered.nix" >/dev/null
pkl-nix-tools generate
[[ $(head -n 1 .pkl-nix-tools/flake.nix) == '# GENERATED BY pkl-nix-tools FROM flake.pkl. DO NOT EDIT.' ]]
grep -q 'description = "first"' .pkl-nix-tools/flake.nix
[[ ! -e flake.nix && ! -e .pkl-nix-tools/flake.lock ]]
nix-instantiate --parse .pkl-nix-tools/flake.nix >/dev/null

export TOOL_TEST_NO_PKL=1
./flake.pkl build .#hello --no-link
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *' build '* ]]
[[ " ${argv[*]} " == *"path:${project// /%20}?dir=.pkl-nix-tools#hello"* ]]
[[ flake.lock -ef .pkl-nix-tools/flake.lock ]]
[[ " ${argv[*]} " != *' --reference-lock-file '* && " ${argv[*]} " != *' --output-lock-file '* ]]
mapfile -d '' -t lock_argv < "$TOOL_TEST_LOCK_LOG"
[[ " ${lock_argv[*]} " == *' flake lock '* && " ${lock_argv[*]} " == *' --output-lock-file '* ]]
rm -f "$TOOL_TEST_LOCK_LOG"
pkl-nix-tools build --no-write-lock-file
[[ ! -e $TOOL_TEST_LOCK_LOG ]]

pkl-nix-tools build --out-link 'result with spaces'
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *"path:${project// /%20}?dir=.pkl-nix-tools --out-link result with spaces"* ]]

./flake.pkl develop --command bash -c true
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *"path:${project// /%20}?dir=.pkl-nix-tools --command bash -c true"* ]]

./flake.pkl flake update
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *"flake update"* ]]
[[ " ${argv[*]} " == *"--flake path:${project// /%20}?dir=.pkl-nix-tools"* ]]

# Nix option values, program arguments and external references are preserved.
./flake.pkl run .#hello -- . '.#unchanged' 'two words'
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ ${argv[-3]} == . && ${argv[-2]} == '.#unchanged' && ${argv[-1]} == 'two words' ]]
pkl-nix-tools build --eval-store . --override-input source . --no-link
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ "${argv[*]}" == *'--eval-store . --override-input source . --no-link' ]]
pkl-nix-tools build 'github:example/flake#hello' --no-link
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ "${argv[*]}" != *'--output-lock-file'* && "${argv[*]}" == *'github:example/flake#hello --no-link' ]]
pkl-nix-tools build --expr 'builtins.toFile "value" "hello"'
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " != *'path:'* && " ${argv[*]} " != *'--output-lock-file'* ]]
pkl-nix-tools flake update nixpkgs
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ ${argv[-1]} == nixpkgs && " ${argv[*]} " != *'--output-lock-file'* ]]
pkl-nix-tools flake update --flake github:example/flake nixpkgs
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " != *'--output-lock-file'* && ${argv[-1]} == nixpkgs ]]

if TOOL_TEST_EXIT=37 ./flake.pkl run .#hello; then exit 1; else
  [[ $? == 37 ]]
fi

unset TOOL_TEST_NO_PKL
printf 'description = "second"\n' > value.pkl
pkl-nix-tools build
grep -q 'description = "second"' .pkl-nix-tools/flake.nix

# Failed rendering must leave the previously generated flake and fingerprint intact.
cp .pkl-nix-tools/flake.nix "$work/good.nix"
cp .pkl-nix-tools/fingerprint "$work/good.fingerprint"
printf 'broken Pkl syntax\n' > value.pkl
if pkl-nix-tools generate >"$work/error.log" 2>&1; then exit 1; fi
cmp .pkl-nix-tools/flake.nix "$work/good.nix"
cmp .pkl-nix-tools/fingerprint "$work/good.fingerprint"
printf 'description = "second"\n' > value.pkl

# Changes imported through PklProject invalidate the cache too.
printf 'amends "pkl:Project"\n' > project-base.pkl
printf 'amends "project-base.pkl"\n' > PklProject
pkl-nix-tools generate
printf '// changed settings\n' >> project-base.pkl
if TOOL_TEST_NO_PKL=1 pkl-nix-tools build >"$work/error.log" 2>&1; then exit 1; fi
pkl-nix-tools generate
mkdir -p nested
(cd nested && TOOL_TEST_NO_PKL=1 pkl-nix-tools build)
# A shebang invocation locates the flake even from an unrelated directory.
(cd "$work" && TOOL_TEST_NO_PKL=1 "$project/flake.pkl" develop --command true)
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *"path:${project// /%20}?dir=.pkl-nix-tools --command true"* ]]

# A changed Pkl dependency refreshes the cached launcher before running Nix.
cat > launcher-source.pkl <<EOF
import "$repo/Bootstrap.pkl" as Tool
output { text = Tool.output.text }
EOF
sed -i "s|import(\"$repo/Bootstrap.pkl\")|import(\"launcher-source.pkl\")|" flake.pkl
./flake.pkl generate
cat > launcher-source.pkl <<EOF
import "$repo/Bootstrap.pkl" as Tool
output { text = Tool.output.text + "\\n# bootstrap upgraded\\n" }
EOF
./flake.pkl build
grep -Fq '# bootstrap upgraded' .pkl-nix-tools/run
TOOL_TEST_NO_PKL=1 ./flake.pkl build

rm -rf .pkl-nix-tools
(cd "$work" && "$project/flake.pkl" generate)
[[ -f .pkl-nix-tools/flake.nix && -f .pkl-nix-tools/fingerprint ]]

(
    mkdir -p "$work/checkout"
    cp "$repo/PklProject" "$repo/PklProject.deps.json" "$repo/Bootstrap.pkl" "$repo/install.pkl" "$repo/pkl-nix-tools" "$work/checkout/"
    cp -R "$repo/example" "$work/checkout/example"
    cd "$work/checkout/example"
    pkl project resolve >/dev/null
    pkl-nix-tools generate
    nix-instantiate --parse .pkl-nix-tools/flake.nix >/dev/null
    grep -Fq '../message.txt' .pkl-nix-tools/flake.nix
    [[ -f flake.lock && ! -e flake.nix && flake.lock -ef .pkl-nix-tools/flake.lock ]]
)

printf 'pkl-nix-tools tests passed\n'
