#!/usr/bin/env bash
set -euo pipefail

repo=$(cd -P -- "$(dirname -- "$0")" && pwd)
export JAVA_TOOL_OPTIONS="${JAVA_TOOL_OPTIONS:+$JAVA_TOOL_OPTIONS }-XX:-UsePerfData"
work=$(mktemp -d '/tmp/pkl-nix-tools-test.XXXXXXXX')
trap 'rm -rf -- "$work"' EXIT
mkdir -p "$work/bin" "$work/project with spaces"
project=$work/project\ with\ spaces
real_nix=$(command -v nix)
real_pkl=$(command -v pkl)

cat > "$work/bin/nix" <<'EOF'
#!/usr/bin/env bash
if [[ " $* " == *' hash file '* ]]; then exec "$REAL_NIX" "$@"; fi
printf '%s\0' "$@" > "$TOOL_TEST_LOG"
exit "${TOOL_TEST_EXIT:-0}"
EOF
cat > "$work/bin/pkl" <<'EOF'
#!/usr/bin/env bash
if [[ ${TOOL_TEST_NO_PKL:-0} == 1 ]]; then exit 99; fi
exec "$REAL_PKL" "$@"
EOF
chmod +x "$work/bin/nix" "$work/bin/pkl"
export REAL_NIX=$real_nix REAL_PKL=$real_pkl TOOL_TEST_LOG=$work/nix.args
export PATH="$repo:$work/bin:$PATH"

cat > "$project/flake.pkl" <<EOF
#!/usr/bin/env -S pkl eval
import "value.pkl" as Value
output {
  text = "{ description = \"" + Value.description + "\"; outputs = { self, ... }: { }; }"
}
EOF
chmod +x "$project/flake.pkl"
printf 'description = "first"\n' > "$project/value.pkl"

cd "$project"
./flake.pkl > "$work/rendered.nix"
nix-instantiate --parse "$work/rendered.nix" >/dev/null
pkl-nix-tools generate
[[ $(head -n 1 .pkl-nix-tools/flake.nix) == '# GENERATED BY pkl-nix-tools FROM flake.pkl. DO NOT EDIT.' ]]
grep -q 'description = "first"' .pkl-nix-tools/flake.nix
[[ ! -e flake.nix && ! -e .pkl-nix-tools/flake.lock ]]
nix-instantiate --parse .pkl-nix-tools/flake.nix >/dev/null

export TOOL_TEST_NO_PKL=1
pkl-nix-tools build .#hello --no-link
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *' build '* ]]
[[ " ${argv[*]} " == *"path:${project// /%20}?dir=.pkl-nix-tools#hello"* ]]
[[ " ${argv[*]} " == *"$project/flake.lock"* ]]

pkl-nix-tools build --out-link 'result with spaces'
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *"path:${project// /%20}?dir=.pkl-nix-tools --out-link result with spaces"* ]]

pkl-nix-tools develop --command bash -c true
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *"path:${project// /%20}?dir=.pkl-nix-tools --command bash -c true"* ]]

pkl-nix-tools flake update
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " == *"flake update"* ]]
[[ " ${argv[*]} " == *"--flake path:${project// /%20}?dir=.pkl-nix-tools"* ]]

# Nix option values, program arguments and external references are preserved.
pkl-nix-tools run .#hello -- . '.#unchanged' 'two words'
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ ${argv[-3]} == . && ${argv[-2]} == '.#unchanged' && ${argv[-1]} == 'two words' ]]
pkl-nix-tools build --eval-store . --override-input source . --no-link
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ "${argv[*]}" == *'--eval-store . --override-input source . --no-link' ]]
pkl-nix-tools build 'github:example/flake#hello' --no-link
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ "${argv[*]}" != *'--output-lock-file'* && "${argv[*]}" == *'github:example/flake#hello --no-link' ]]
pkl-nix-tools build --expr 'builtins.toFile "value" "hello"'
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " != *'path:'* && " ${argv[*]} " != *'--output-lock-file'* ]]
pkl-nix-tools flake update nixpkgs
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ ${argv[-1]} == nixpkgs && " ${argv[*]} " == *'--output-lock-file'* ]]
pkl-nix-tools flake update --flake github:example/flake nixpkgs
mapfile -d '' -t argv < "$TOOL_TEST_LOG"
[[ " ${argv[*]} " != *'--output-lock-file'* && ${argv[-1]} == nixpkgs ]]

if TOOL_TEST_EXIT=37 pkl-nix-tools run .#hello; then exit 1; else
  [[ $? == 37 ]]
fi

unset TOOL_TEST_NO_PKL
printf 'description = "second"\n' > value.pkl
pkl-nix-tools build
grep -q 'description = "second"' .pkl-nix-tools/flake.nix

# Failed rendering must leave the previously generated flake and fingerprint intact.
cp .pkl-nix-tools/flake.nix "$work/good.nix"
cp .pkl-nix-tools/fingerprint "$work/good.fingerprint"
printf 'broken Pkl syntax\n' > value.pkl
if pkl-nix-tools generate >"$work/error.log" 2>&1; then exit 1; fi
cmp .pkl-nix-tools/flake.nix "$work/good.nix"
cmp .pkl-nix-tools/fingerprint "$work/good.fingerprint"
printf 'description = "second"\n' > value.pkl

# Changes imported through PklProject invalidate the cache too.
printf 'amends "pkl:Project"\n' > project-base.pkl
printf 'amends "project-base.pkl"\n' > PklProject
pkl-nix-tools generate
printf '// changed settings\n' >> project-base.pkl
if TOOL_TEST_NO_PKL=1 pkl-nix-tools build >"$work/error.log" 2>&1; then exit 1; fi
pkl-nix-tools generate
mkdir -p nested
(cd nested && TOOL_TEST_NO_PKL=1 pkl-nix-tools build)

rm -rf .pkl-nix-tools
pkl-nix-tools generate
[[ -f .pkl-nix-tools/flake.nix && -f .pkl-nix-tools/fingerprint ]]

(
    mkdir -p "$work/checkout"
    cp "$repo/PklProject" "$repo/PklProject.deps.json" "$repo/imports.pkl" "$repo/install.pkl" "$repo/pkl-nix-tools" "$work/checkout/"
    cp -R "$repo/example" "$work/checkout/example"
    cd "$work/checkout/example"
    pkl project resolve >/dev/null
    pkl-nix-tools generate
    nix-instantiate --parse .pkl-nix-tools/flake.nix >/dev/null
    grep -Fq '../message.txt' .pkl-nix-tools/flake.nix
    [[ -f flake.lock && ! -e flake.nix && ! -e .pkl-nix-tools/flake.lock ]]
)

printf 'pkl-nix-tools tests passed\n'
